<?php

return [
    'instagram' => [
        'label' => 'Instagram',
        'icon' => 'instagram',
        'type' => 'username',
        'prefix' => '@',
        'placeholder' => 'creator',
        'url_template' => 'https://instagram.com/{value}',
    ],
    'tiktok' => [
        'label' => 'TikTok',
        'icon' => 'tiktok',
        'type' => 'username',
        'prefix' => '@',
        'placeholder' => 'creator',
        'url_template' => 'https://www.tiktok.com/@{value}',
    ],
    'youtube' => [
        'label' => 'YouTube',
        'icon' => 'youtube',
        'type' => 'username',
        'prefix' => '@',
        'placeholder' => 'kanal',
        'url_template' => 'https://www.youtube.com/@{value}',
    ],
    'x' => [
        'label' => 'X',
        'icon' => 'x',
        'type' => 'username',
        'prefix' => '@',
        'placeholder' => 'creator',
        'url_template' => 'https://x.com/{value}',
    ],
    'spotify' => [
        'label' => 'Spotify',
        'icon' => 'spotify',
        'type' => 'url',
        'placeholder' => 'https://open.spotify.com/artist/…',
        'url_template' => '{value}',
    ],
    'github' => [
        'label' => 'GitHub',
        'icon' => 'github',
        'type' => 'username',
        'prefix' => '@',
        'placeholder' => 'username',
        'url_template' => 'https://github.com/{value}',
    ],
    'linkedin' => [
        'label' => 'LinkedIn',
        'icon' => 'linkedin',
        'type' => 'username',
        'placeholder' => 'username',
        'url_template' => 'https://www.linkedin.com/in/{value}',
    ],
    'facebook' => [
        'label' => 'Facebook',
        'icon' => 'facebook',
        'type' => 'username',
        'placeholder' => 'seite',
        'url_template' => 'https://facebook.com/{value}',
    ],
    'threads' => [
        'label' => 'Threads',
        'icon' => 'threads',
        'type' => 'username',
        'prefix' => '@',
        'placeholder' => 'creator',
        'url_template' => 'https://www.threads.net/@{value}',
    ],
    'email' => [
        'label' => 'E-Mail',
        'icon' => 'email',
        'type' => 'email',
        'placeholder' => 'hallo@beispiel.de',
        'url_template' => 'mailto:{value}',
    ],
    'whatsapp' => [
        'label' => 'WhatsApp',
        'icon' => 'whatsapp',
        'type' => 'phone',
        'prefix' => '+',
        'placeholder' => '491234567890',
        'url_template' => 'https://wa.me/{value}',
    ],
    'custom' => [
        'label' => 'Eigener Link',
        'icon' => 'link',
        'type' => 'custom',
    ],
];
