<?php

return [
    'instagram' => [
        'icon' => 'instagram',
        'color' => '#E4405F',
        'type' => 'username',
        'prefix' => '@',
        'placeholder' => 'creator',
        'url_template' => 'https://instagram.com/{value}',
    ],
    'tiktok' => [
        'icon' => 'tiktok',
        'color' => '#000000',
        'type' => 'username',
        'prefix' => '@',
        'placeholder' => 'creator',
        'url_template' => 'https://www.tiktok.com/@{value}',
    ],
    'youtube' => [
        'icon' => 'youtube',
        'color' => '#FF0000',
        'type' => 'username',
        'prefix' => '@',
        'placeholder' => 'kanal',
        'url_template' => 'https://www.youtube.com/@{value}',
    ],
    'x' => [
        'icon' => 'x',
        'color' => '#000000',
        'type' => 'username',
        'prefix' => '@',
        'placeholder' => 'creator',
        'url_template' => 'https://x.com/{value}',
    ],
    'spotify' => [
        'icon' => 'spotify',
        'color' => '#1DB954',
        'type' => 'url',
        'placeholder' => 'https://open.spotify.com/artist/…',
        'url_template' => '{value}',
    ],
    'github' => [
        'icon' => 'github',
        'color' => '#181717',
        'type' => 'username',
        'prefix' => '@',
        'placeholder' => 'username',
        'url_template' => 'https://github.com/{value}',
    ],
    'linkedin' => [
        'icon' => 'linkedin',
        'color' => '#0A66C2',
        'type' => 'username',
        'placeholder' => 'username',
        'url_template' => 'https://www.linkedin.com/in/{value}',
    ],
    'facebook' => [
        'icon' => 'facebook',
        'color' => '#1877F2',
        'type' => 'username',
        'placeholder' => 'seite',
        'url_template' => 'https://facebook.com/{value}',
    ],
    'threads' => [
        'icon' => 'threads',
        'color' => '#000000',
        'type' => 'username',
        'prefix' => '@',
        'placeholder' => 'creator',
        'url_template' => 'https://www.threads.net/@{value}',
    ],
    'email' => [
        'icon' => 'email',
        'color' => '#6366f1',
        'type' => 'email',
        'placeholder' => 'hallo@beispiel.de',
        'url_template' => 'mailto:{value}',
    ],
    'whatsapp' => [
        'icon' => 'whatsapp',
        'color' => '#25D366',
        'type' => 'phone',
        'prefix' => '+',
        'placeholder' => '491234567890',
        'url_template' => 'https://wa.me/{value}',
    ],
    'custom' => [
        'icon' => 'link',
        'color' => '#6366f1',
        'type' => 'custom',
    ],
];
